# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca0f27864ed023716af056a4ab038d3b79e85c33f7a1cb182bd672c31456388a6151ee9c2ff2d3afe3cd30edb5ca51201f8b65fcab65a846c44e3c1e8cca0775

test:
  secret_key_base: 6f06a9d65aa5d050368f0d25e039310d938d408e77f30b9250d0187d00f08234ee4628f8eb5837cfa2d54a3fa74b1fa0c9150033613d8998b3ad27a25fdda113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
